---

- name: Configure acng.conf
  ansible.builtin.lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: "^{{ item.key }}: "
    line: "{{ item.key }}: {{ item.value['value'] | default(item.value) }}"
    state: "{{ item.value['ensure'] | default('present') }}"
  loop: "{{ lookup('dict', acng_config, wantlist=True) }}"
  notify:
    - "Restart {{ acng_service_name }}"

- name: Configure security.conf
  ansible.builtin.lineinfile:
    dest: /etc/apt-cacher-ng/security.conf
    regexp: "^AdminAuth:"
    line: "AdminAuth: {{ acng_admin_name }}:{{ acng_admin_password }}"
    state: "{{ (acng_admin_state == 'present' and acng_admin_name) | ternary('present', 'absent') }}"
  notify:
    - "Restart {{ acng_service_name }}"
