---
# handlers file for acng
- name: "Restart {{ acng_service_name }}"
  when: acng_service_state == "started"
  ansible.builtin.service:
    name: "{{ acng_service_name }}"
    state: restarted
    use: "{{ acng_service_use | default(omit) }}"
