---
- name: Converge
  hosts: all
  vars:
    acng_service_use: sysvinit
    acng_config:
      RedirMax: 5
      Remap-epel:
        ensure: absent
      ExThreshold:
        value: 3
      PassThroughPattern:
        value: '^(.*):443$'
        ensure: absent
  tasks:
    - name: "Include role ansible-role-acng"
      ansible.builtin.include_role:
        name: "ansible-role-acng"
