---
- name: Converge
  hosts: all
  vars:
    acng_test: salut
    acng_service_use: sysvinit
    acng_config_default:
      RedirMax:
        value: 5
    acng_config:
      Remap-epel:
        ensure: absent
      ExThreshold:
        value: 3
  tasks:
    - name: "Include role ansible-role-acng"
      ansible.builtin.include_role:
        name: "ansible-role-acng"
